FROM docker.io/library/debian:13-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 python3-pip python3-venv python3-dev \
    build-essential pkg-config \
    libpq-dev libmagic1 libzbar0 \
    tesseract-ocr tesseract-ocr-rus tesseract-ocr-eng \
    unpaper ghostscript icc-profiles-free \
    poppler-utils gnupg curl \
    redis-server && \
    rm -rf /var/lib/apt/lists/*
RUN useradd -r -u 10001 -m paperless && \
    mkdir -p /app /data/consume /data/media /data/data /config /run/redis && \
    chown -R paperless:paperless /app /data /config /run/redis
USER paperless
RUN python3 -m venv /app/venv && \
    /app/venv/bin/pip install --no-cache-dir paperless-ngx gunicorn uvicorn
EXPOSE 8012
COPY entrypoint.sh /app/entrypoint.sh
ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]
