---
enable_vaultwarden: true

vaultwarden_port: 8010
vaultwarden_data_dir: "{{ opt_base }}/vaultwarden/data"
vaultwarden_config_dir: "{{ opt_base }}/vaultwarden/config"
# vaultwarden_admin_token — defined in group_vars/passwords.yml
vaultwarden_signups_allowed: "true"
vaultwarden_version: "1.35.4"
vaultwarden_tag: "{{ vaultwarden_version }}"
vaultwarden_image: "{{ (container_registry ~ '/' if container_registry else '') }}{{ (container_namespace ~ '/' if container_namespace else '') }}vaultwarden"
vaultwarden_image_full: "{{ vaultwarden_image }}:{{ vaultwarden_tag }}"
