---
enable_opencloud: true

opencloud_port: 8014
opencloud_data_dir: "{{ opt_base }}/opencloud/data"
opencloud_config_dir: "{{ opt_base }}/opencloud/config"
opencloud_admin_user: admin
opencloud_upload_max_size: 10G
opencloud_version: "6.0.0"
opencloud_tag: "{{ opencloud_version }}"
opencloud_image: "{{ (container_registry ~ '/' if container_registry else '') }}{{ (container_namespace ~ '/' if container_namespace else '') }}opencloud"
opencloud_image_full: "{{ opencloud_image }}:{{ opencloud_tag }}"
