---
enable_searxng: true

searxng_port: 8009
searxng_data_dir: "{{ opt_base }}/searxng/data"
searxng_config_dir: "{{ opt_base }}/searxng/config"
searxng_secret_key: changeme-generate-long-random-string
searxng_base_url: "/searxng/"
