FROM docker.io/library/debian:13-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends transmission-daemon && \
    rm -rf /var/lib/apt/lists/*
RUN useradd -r -u 10001 -m transmission && \
    mkdir -p /config /downloads /watch && \
    chown -R transmission:transmission /config /downloads /watch
USER transmission
EXPOSE 8003 51413
ENTRYPOINT ["transmission-daemon", "--foreground", "--config-dir", "/config"]
